# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Drumsensei
email: mike@drumsensei.com
description: >- # this means to ignore newlines until "baseurl:"
  Betwixt music and code
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://drumsensei.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: drumsensei
# github_username:  m2mathew

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Speaking
   url: /speaking
 - title: Contact
   url: /contact

# Social
social:
   github: m2mathew
   twitter: drumsensei
   facebook: m2mathew
   email: mike@drumsensei.com

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
plugins:
  - jekyll-feed
  - jekyll-avatar
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# google_analytics: "UA-58263416-1"
